version: '2'
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

    command: dockerize -wait tcp://mongodb:27017 -timeout 300s

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
